# Generated by Django 4.0.6 on 2022-07-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Dni', models.IntegerField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('age', models.DateField()),
            ],
        ),
    ]
