# Generated by Django 4.0.6 on 2022-07-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Family', '0002_alter_family_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='Dni',
            field=models.IntegerField(default='unknow'),
        ),
        migrations.AlterField(
            model_name='family',
            name='age',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
